### ISSUE TITLE
您好，请问可以分享下代码吗？想学习一下~    

### ISSUE THREAD

**Issue by zhLeon521** [Chuyun-Shen/Interactive-Medical-Image-Segmentation-with-MARL#1]

**Comment by Chuyun-Shen** [comment]
Thank you for your interest in our project! We appreciate your enthusiasm and understand that you're eager to reproduce our experiments. As mentioned, the code has not been completely organized yet, but we're happy to share an unorganized version with you in the meantime. Please note that this version does not represent the final version of the code, and there may be some inconsistencies or issues.

You can download the unorganized code from the following Baidu Cloud link:

Baidu Cloud Link: https://pan.baidu.com/s/1sXINyYTwgHPSMjwKAAkvTw
Password: fcuc

We hope this helps you get started with reproducing our experiments. If you encounter any issues or have questions, please don't hesitate to reach out. We'll be more than happy to assist you. Additionally, we'll keep you updated on the progress of organizing the code and will notify you once the final version is available.

Thank you for your understanding and support!
